CREATE TABLE tasks (
id INTEGER PRIMARY KEY AUTOINCREMENT,
project_id INTEGER REFERENCES projects (id) ON DELETE CASCADE ON UPDATE CASCADE,
user_id INTEGER REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,  
task_name TEXT,
start_date TEXT,
end_date TEXT
);