CREATE TABLE sub_task (
id SERIAL PRIMARY KEY
task_id INTEGER REFERENCES task (id) ON DELETE CASCADE ON UPDATE CASCADE,
user_id INTEGER REFERENCES user (id) ON DELETE CASCADE ON UPDATE CASCADE, 
sub_task_name TEXT,
start_date TEXT,
end_date TEXT
);