CREATE TABLE sub_tasks (
id INTEGER PRIMARY KEY AUTOINCREMENT,
task_id INTEGER REFERENCES tasks (id) ON DELETE CASCADE ON UPDATE CASCADE,
user_id INTEGER REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE, 
sub_task_name TEXT,
start_date TEXT,
end_date TEXT
);